service: serverless-rest-api-with-dynamodb

frameworkVersion: '2'
provider:
  name: aws
  runtime: nodejs14.x
  
      
resources:
  Resources:
    TodosDynamoDbTable:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          -
<<<<<<< HEAD
            AttributeName: OwnerAccountAddress
            AttributeType: S
          -
            AttributeName: NftContractAddress
            AttributeType: S
        KeySchema:
          -
            AttributeName: OwnerAccountAddress
            KeyType: HASH
          -
            AttributeName: NftContractAddress
=======
            AttributeName: AccountAddress
            AttributeType: S
          -
            AttributeName: TransactionID
            AttributeType: S
        KeySchema:
          -
            AttributeName: AccountAddress
            KeyType: HASH
          -
            AttributeName: TransactionID
>>>>>>> 8283f63c02b451b001fedbc5265715b0f8bbf411
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1

